"""Pieces every deck style shares: the cover slide edit and the branding master's
fixed cover/end-card slides. Raw-OOXML only (see scripts/office/); knows nothing
about checklists' findings or any style's own slides."""

import logging
import mimetypes
import re
import shutil
import tempfile
from datetime import datetime
from pathlib import Path

import common
import read_checklist
from office import package, shapes, slides, text

logger = logging.getLogger("deck_shared")

# Slide filenames in "resources/Dataiku Branding Template 2026.pptx" (see the
# anchor warning in build_deck.py: a different base deck must match these).
TITLE_SLIDE = "slide15.xml"
CONTACT_SLIDE = "slide62.xml"                # footer/contact info; the end card of the v2 deck

TITLE_FOOTER_X = 360000  # = build_deck.CONTENT_LEFT
TITLE_FOOTER_Y = 4500000
TITLE_FOOTER_WIDTH = 6506100  # matches slide15's title/subtitle box width
TITLE_FOOTER_HEIGHT = 550000


def truncate(value, limit: int) -> str:
    value = (value or "").strip()
    if len(value) <= limit:
        return value
    return value[: max(0, limit - 1)].rstrip() + "…"


def format_month_year(date_str) -> str:
    if not date_str:
        return ""
    s = str(date_str).strip()
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M", "%Y-%m-%d"):
        try:
            return datetime.strptime(s[: len(fmt) + 2], fmt).strftime("%b %Y")
        except ValueError:
            continue
    m = re.match(r"(\d{4})-(\d{2})-(\d{2})", s)
    if m:
        return datetime(int(m.group(1)), int(m.group(2)), int(m.group(3))).strftime("%b %Y")
    return s


def format_title_metadata_lines(data: read_checklist.ChecklistData) -> list:
    """Bundle/Node-Version/Report-generated as a short footer for the title
    slide, mirroring how the reference deck carries this metadata directly
    on its title slide instead of a dedicated table slide."""
    lines = []
    bundle = data.bundle_metadata.get("Bundle")
    if bundle:
        lines.append(f"Bundle: {truncate(str(bundle), 90)}")
    node_version = data.bundle_metadata.get("Node / Version")
    if node_version:
        lines.append(f"Node / Version: {truncate(str(node_version), 90)}")
    report_generated = data.bundle_metadata.get("Report generated")
    if report_generated:
        lines.append(f"Report generated: {truncate(str(report_generated), 60)}")
    lines.append(f"Generated by Dataiku Review Generator v{common.VERSION}")
    return lines


def add_logo(work_dir: Path, logo_path: Path) -> None:
    """Add the customer logo as a picture on the title slide, positioned
    over the title layout's own 'Customer logo' placeholder box."""
    ext = logo_path.suffix.lstrip(".").lower() or "png"
    content_type = mimetypes.guess_type(logo_path.name)[0] or "image/png"

    media_dir = work_dir / "ppt" / "media"
    media_dir.mkdir(parents=True, exist_ok=True)
    existing = {p.name for p in media_dir.glob("image*.*")}
    n = 1
    while f"image{n}.{ext}" in existing or (media_dir / f"image{n}.{ext}").exists():
        n += 1
    media_name = f"image{n}.{ext}"
    shutil.copyfile(logo_path, media_dir / media_name)

    ct_path = work_dir / "[Content_Types].xml"
    ct_xml = ct_path.read_text(encoding="utf-8")
    if f'Extension="{ext}"' not in ct_xml:
        default = f'<Default ContentType="{content_type}" Extension="{ext}"/>'
        ct_xml = ct_xml.replace("<Default", default + "<Default", 1)
        ct_path.write_text(ct_xml, encoding="utf-8")

    rels_path = work_dir / "ppt" / "slides" / "_rels" / f"{TITLE_SLIDE}.rels"
    rels_xml = rels_path.read_text(encoding="utf-8") if rels_path.exists() else (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>'
    )
    nums = [int(m) for m in re.findall(r'Id="rId(\d+)"', rels_xml)]
    new_rid = f"rId{(max(nums) if nums else 0) + 1}"
    new_rel = (
        f'<Relationship Id="{new_rid}" '
        f'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" '
        f'Target="../media/{media_name}"/>'
    )
    rels_xml = rels_xml.replace("</Relationships>", new_rel + "</Relationships>")
    rels_path.parent.mkdir(parents=True, exist_ok=True)
    rels_path.write_text(rels_xml, encoding="utf-8")

    # Position/size match the title layout's own "Customer logo" placeholder
    # box (slide15.xml, shape "Google Shape;348;p40"), so the image lands
    # exactly where that dashed placeholder box is.
    slide_path = work_dir / "ppt" / "slides" / TITLE_SLIDE
    slide_xml = slide_path.read_text(encoding="utf-8")
    pic_id = text.next_shape_id(slide_xml)
    pic_xml = (
        f'<p:pic><p:nvPicPr><p:cNvPr id="{pic_id}" name="Uploaded Logo"/>'
        f'<p:cNvPicPr preferRelativeResize="0"/><p:nvPr/></p:nvPicPr>'
        f'<p:blipFill><a:blip r:embed="{new_rid}"><a:alphaModFix/></a:blip>'
        f'<a:stretch><a:fillRect/></a:stretch></p:blipFill>'
        f'<p:spPr><a:xfrm><a:off x="1668725" y="182575"/><a:ext cx="1445700" cy="394500"/></a:xfrm>'
        f'<a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr></p:pic>'
    )
    slide_xml = text.insert_shape(slide_xml, pic_xml)
    slide_path.write_text(slide_xml, encoding="utf-8")


# --------------------------------------------------------------------------
# Orchestration
# --------------------------------------------------------------------------


def build_cover(work_dir: Path, data, customer: str, logo_path: Path | None) -> None:
    """Edit the title slide of an unpacked base deck in place: customer name,
    subtitle, bundle-metadata footer and (optionally) the customer logo.
    Shared by every deck style that keeps the branding master's cover."""
    report_date_str = data.bundle_metadata.get("Report generated") or data.bundle_metadata.get("Diagnosis generated")
    slide_path = work_dir / "ppt" / "slides" / TITLE_SLIDE
    slide_xml = slide_path.read_text(encoding="utf-8")
    slide_xml = text.replace_text_run(
        slide_xml, "This is your presentation title, please try best to shorten your title within three lines.",
        customer.upper(),
    )
    subtitle = f"Platform Review — {format_month_year(report_date_str)}" if report_date_str else "Platform Review"
    slide_xml = text.replace_text_run(slide_xml, "Subtitle if needed and make it short.", subtitle)
    slide_xml = text.replace_text_run(slide_xml, "Customer logo", "", required=False)

    metadata_lines = format_title_metadata_lines(data)
    if metadata_lines:
        shape_id = text.next_shape_id(slide_xml)
        footer_xml = shapes.text_box(
            shape_id, "Bundle metadata", TITLE_FOOTER_X, TITLE_FOOTER_Y, TITLE_FOOTER_WIDTH, TITLE_FOOTER_HEIGHT,
            paragraphs=[[{"text": line, "size": 900, "color": "8A93A3"}] for line in metadata_lines],
        )
        slide_xml = text.insert_shape(slide_xml, footer_xml)

    slide_path.write_text(slide_xml, encoding="utf-8")
    if logo_path:
        logger.info("Adding customer logo: %s", logo_path)
        add_logo(work_dir, logo_path)


def build_cover_and_end_deck(base_deck: Path, data: read_checklist.ChecklistData, customer: str,
                             logo_path: Path | None, output_path: Path) -> Path:
    """Write a two-slide .pptx -- the edited cover, then the branding master's contact
    slide -- for a style that adds its own body slides in between. Same edit and
    orphan cleanup the v1 build applies to these two slides."""
    with tempfile.TemporaryDirectory(prefix="deckcover_") as tmp:
        work_dir = Path(tmp) / "unpacked"
        logger.info("Unpacking base deck: %s", base_deck)
        package.unpack(base_deck, work_dir)
        build_cover(work_dir, data, customer, logo_path)
        for filename in slides.list_slide_order(work_dir):
            if filename not in (TITLE_SLIDE, CONTACT_SLIDE):
                slides.delete_slide(work_dir, filename)
        logger.info("Cleaned up orphaned parts: %s", slides.clean_orphans(work_dir))
        output_path.parent.mkdir(parents=True, exist_ok=True)
        package.repack(work_dir, output_path)
    return output_path
